### ISSUE TITLE
Problems during installation

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Livruen/Icinga2-Dashboard-with-sound#5]
Hello I am very interested in your module.

My goal is to output the startrek sound in icinga2db when a host is down. I have installed the module.

Unfortunately I don't see any change. Can you help me here and tell me what I have forgotten?

Thank you very much!

David

**Comment by Livruen** [comment]
Hello David,

Sorry for the late response. I am currently in parental leave and I am not
able to help you at this moment. I will be available in September 2024.

Kind regards
Livruen

David Franzen ***@***.***> schrieb am Fr., 15. Dez. 2023,
19:18:
